= Legal Notices

== License

The UMRS (Unclassified MLS Reference System) project is licensed under the MIT License.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the “Software”), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

== Documentation License

Unless otherwise stated, this documentation is provided under the same MIT
License as the UMRS software components.

== Trademarks

Red Hat and Red Hat Enterprise Linux are trademarks or registered trademarks
of Red Hat, Inc. or its subsidiaries in the United States and other countries.

All other trademarks referenced in this documentation are the property of
their respective owners.

The use of trademarks in this documentation is for informational purposes
only and does not imply endorsement by the trademark holders.

== Disclaimer

This project and its documentation are provided for educational and
demonstration purposes. They are not intended to represent an accredited
or certified system, nor do they constitute security advice or compliance
guidance for any specific regulatory regime.

Users are responsible for evaluating the suitability of this project for
their own environments and requirements.

